stages:
  - test
  - package
  - push

test:
  stage: test
  only:
    - ^feature\/^CU-.*$
  script:
    - mvn clean test
  tags:
    - shell

package:
  stage: package
  only:
    - develop
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
  tags:
    - shell

push:
  stage: push
  variables:
    IMAGE_NAME: $CI_REGISTRY/portal/$CI_PROJECT_NAME
  only:
    - develop
  script:
    - docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:version .
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD CI_REGISTRY
    - docker push $IMAGE_NAME:latest
    - docker image rm $IMAGE_NAME:latest
  tags:
    - shell