stages:
  - test
  - package
  - push
  - deploy

test:
  stage: test
  only:
    - ^feature\/^CU-.*$
  script:
    - mvn clean test
  tags:
    - shell

package:
  stage: package
  only:
    - develop
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
  tags:
    - shell

push:
  stage: push
  variables:
    IMAGE_NAME: $CI_REGISTRY/portal/$CI_PROJECT_NAME
  only:
    - develop
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME:latest
    - docker image rm $IMAGE_NAME:latest
  tags:
    - shell

deploy:
  stage: deploy
 # image: gitlab.innoconsulting.ru:5050/portal/awx-cli:latest
  script:
#    - awx 
#      --conf.host $AWX_HOST 
#      --conf.username $AWX_USERNAME 
#      --conf.password $AWX_PASSWORD 
#      --conf.insecure 
#      -f human job_templates launch 'rollout container application template' 
#      --monitor --filter status
    - curl --insecure -u $AWX_USERNAME:$AWX_PASSWORD $AWX_HOST/api/v2/job_templates/9/launch/
  tags:
    - shell
