- hosts: 176.113.82.235
  tasks:
    - name: Recursively find /tmp files older than 2 days
      find:
        paths: /home/cuerp
        file_type: any
      register: out
        
    - debug:
        var: out
