openapi: "3.0.3"

info:
  title: "profile_backend"
  description: "profile_backend"
  version: "1.0.0"

paths:

  /profile/dropdown/{listId}/{fieldId}:
    get:
      description: "Получение всех dropdown опций по Field ID (приходит вместе с профилем)"

      parameters:
        - name: listId
          in: path
          required: true
          description: "Field ID для поиска"
          schema:
            type: integer

        - name: fieldId
          in: path
          required: true
          description: "Field ID для поиска"
          schema:
            type: string

      responses:
        200:
          description: "Все dropdown опции"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DropdownOptions"

  /profile/{egarId}:
    get:
      description: "Получение профиля сотрудника по Egar ID (Где взять: [egarId]@egartech.ru)"

      parameters:
        - name: egarId
          in: path
          required: true
          schema:
            type: string
          description: "Egar ID сотрудника"

      responses:

        200:
          description: "Профиль сотрудника без Sickday"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"

        400:
          description: "Неверная карточка сотрудника"

        404:
          description: "Сотрудник не найден"

components:
  schemas:

    DropdownOptions:
      type: array
      items:
        $ref: "#/components/schemas/DropdownOption"

    DropdownOption:
      type: object
      properties:
        name:
          type: string
          example: "Разработчик"
        index:
          type: integer
          example: 0

    Experience:
      type: object
      properties:
        years:
          type: integer
          example: 1
        months:
          type: integer
          example: 7

    Profile:
      type: object
      properties:
        list_id:
          type: integer
          example: 180311895

        egar_id:
          type: string
          example: "MPetrova"

        position_options_id:
          type: string
          example: "33064c03-b21f-4f93-b74d-b2ef4b081208"

        position:
          $ref: "#/components/schemas/DropdownOption"

        grade:
          type: string
          example: "Middle"

        stack:
          type: array
          items:
            type: string
          example: ["Java", "Spring"]

        avatar_url:
          type: string
          example: "https://t4597045.p.clickup-attachments.com/t4597045/e19a8d64-ba5b-47ce-84e6-dde62092d5f1_large.png"

        onboard_date:
          type: string
          example: "1662032329524"

        birth_date:
          type: string
          example: "1362032329524"

        egar_experience:
          $ref: "#/components/schemas/Experience"

        work_email:
          type: string
          example: "pupkin@egar.com"

        telegram:
          type: string
          example: "@petr"

        skype:
          type: string
          example: "pupkin@egar.com"

        whatsapp:
          type: string
          example: "https://wa.me/14134567890"



